### ISSUE TITLE
Auto generate example readme.mds

### ISSUE THREAD

**Issue by cprivitere** [equinix-labs/terraform-equinix-kubernetes-addons#43]
For some reason the terraform-doc code errors out when set to recursive. This prevents it from auto generating readme.md's for the examples.

**Comment by ocobles** [comment]
It seems that with the last update it's working well. This last generated PR https://github.com/equinix-labs/terraform-equinix-kubernetes-addons/pulls is taking into account all the directories. Can we close this and #40 #41 #42 issues?

**Comment by ocobles** [comment]
fixed in https://github.com/equinix-labs/terraform-equinix-kubernetes-addons/commit/9582e52606b80e47f3fa7a951921438c3da17eb6
